version: '3'

services:
  web:
    image: python:3.12
    container_name: django-cookbook-app
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./mirgovorit/.env

  # PostgreSQL database
  db:
    image: postgres:latest
    container_name: cookbook-db
    env_file:
      - ./mirgovorit/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
